---
- name: Install Docker on Ubuntu
  hosts: all
  become: yes
  tasks:
    - name: Update apt package index
      command: apt-get update

    - name: Install required packages
      command: apt install -y apt-transport-https ca-certificates curl gnupg lsb-release

    - name: Add Docker’s official GPG key
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

    - name: Set up the stable repository
      command: echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

    - name: Update apt package index again
      command: apt-get update

    - name: Install Docker Engine
      command: apt-get install -y docker-ce
